#!/usr/bin/env python3
"""
ARK-AI-OS Integration Test
Autonomously generated by Autonomous Expansion Engine
"""

import os
import sys
import importlib.util

def test_component_import(component_path):
    """Test if a component can be imported"""
    try:
        spec = importlib.util.spec_from_file_location("test_module", component_path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return True
    except Exception as e:
        print(f"Failed to import {component_path}: {e}")
        return False

def run_integration_test():
    """Run comprehensive integration test"""
    workspace = "/home/deflex/ark-ai-os-workspace"
    components_tested = 0
    components_passed = 0

    # Test key components
    key_components = [
        "hootl_autonomy_loop.py",
        "noa_autonomous_optimizer.py",
        "offline_self_update_system.py",
        "cecca/cecca_root_capsule.py",
        "stem/stem_layer.py",
        "knowledge_capsules/kidx/cas_index.py",
        "control_plane/directory_registry.py",
        "execution_plane/dag_runner.py"
    ]

    for component in key_components:
        component_path = os.path.join(workspace, component)
        if os.path.exists(component_path):
            components_tested += 1
            if test_component_import(component_path):
                components_passed += 1
                print(f"✓ {component}")
            else:
                print(f"✗ {component}")
        else:
            print(f"? {component} (file not found)")

    print(f"
Integration Test Results:")
    print(f"Components tested: {components_tested}")
    print(f"Components passed: {components_passed}")
    print(f"Success rate: {components_passed}/{components_tested}")

    return components_passed == components_tested

if __name__ == "__main__":
    success = run_integration_test()
    sys.exit(0 if success else 1)
