name: docs-refresh
on:
  merge:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.workspace/sop/**'
      - 'workflow/**'
      - 'agents/src/implementations/documentation/**'

variables:
  DOC_AGENT_BIN: 'cargo run -p noa_agents --bin documentation_sync'
  DOC_APPROVALS_REQUIRED:
    - doc-lead
    - release-manager

stages:
  - validate
  - docs
  - verify

jobs:
  validate:
    stage: validate
    script:
      - cargo fmt --check
      - cargo test -p noa_agents writes_expected_artifacts

  doc-refresh:
    stage: docs
    needs:
      - validate
    script:
      - mkdir -p build_output
      - echo "Generating diff summary"
      - git diff --name-status HEAD^ HEAD > build_output/doc_diff.txt
      - echo "Triggering documentation pipeline"
      - cicd trigger-doc-pipeline \
          --commit "$CI_COMMIT_SHA" \
          --diff-summary "$(head -n 20 build_output/doc_diff.txt)" \
          --approvals "${DOC_APPROVALS_REQUIRED[*]}"
      - echo "Running documentation agent"
      - ${DOC_AGENT_BIN} --pipeline-output build_output/doc_diff.txt
    artifacts:
      paths:
        - build_output/doc_diff.txt
    approvals:
      required:
        - doc-lead
        - release-manager

  verify:
    stage: verify
    needs:
      - doc-refresh
    script:
      - echo "Verifying documentation updates"
      - test -f docs/wiki/index.md
      - test -f docs/runbook/index.md
      - echo "Documentation artifacts verified"
